title:  "SD 1.5 — DDIM with noise renormalization"
output_dir: sweeps/noise_fix

examples:
  dataset: data/wild-ti2i
  indices : [0, 5]

fixed:
  num_inference_steps: 50
  guidance_scale: 7.5

axes:
  noise_source:
    values: [random]

  projection:
    # values: [orthonormal]
    values: [coordinate, orthonormal]

  dim_out:
    linspace: [3000, 12000, 5]

  nu:
    values: [1.0, 0.993, 0.9816, 0.9582, 0.9166, 0.8515, 0.7597, 0.6412, 0.4979, 0.3271, 0.0413, 0.0]
    # values: [ 0.8515,  0.6412,  0.3271, 0.1, 0.0413]

  mean_scale: 
    values: [vp, ve]

  eta:
    values: [0.0, 1.0]

  rescale_combined:
    values: [True, False]

  gate_type:
    values: [quadratic, heaviside]
