title:  "SD 1.5 —  Diagnosing"
output_dir: sweeps/test

examples:
  dataset: data/wild-ti2i
  indices : [5]

snapshots:
  enable: true
  steps: [0, 4, 9, 14, 19, 24, 29, 34, 39, 44, 49]

logging:
  mode: both

fixed:
  num_inference_steps: 50
  guidance_scale: 7.5

axes:
  noise_source:
    values: [random]
  nu:
    # values: [1.0, 0.993, 0.9816, 0.9582, 0.9166, 0.8515, 0.7597, 0.6412, 0.4979, 0.3271, 0.0413, 0.0]
    # values: [0.8515, 0.6412, 0.3271, 0.1, 0.0]
    values: [0.9, 0.5, 0.0]

  mean_scale: 
    values: [vp, ve]

  eta:
    values: [0.0]

  scales:
    values: [1.0, 0.5, 0.25, 0.125]

  rescale_combined:
    values: [True, False]

  gate_type:
    values: [quadratic, heaviside]
